apiVersion: v1
kind: ConfigMap
metadata:
  name: keygeneratorconfig
data:
  FUNCTIONS_WORKER_RUNTIME: dotnet                
  EVENTHUB_CONNECTION__clientId: {{ .Values.MSI_CLIENTID }}  
  EVENTHUB_CONNECTION__fullyQualifiedNamespace: {{ print .Values.EVENTHUB_NAMESPACE_NAME ".servicebus.windows.net" }}
  AzureWebJobsStorage__queueServiceUri: {{ print "https://" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ".queue.core.windows.net" }}
  AzureWebJobsStorage__tableServiceUri: {{ print "https://" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ".table.core.windows.net" }}
  AzureWebJobsStorage__blobServiceUri: {{ print "https://" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ".blob.core.windows.net" }}