apiVersion: v1
kind: ConfigMap
metadata:
  name: keygeneratorconfig
  namespace: {{ .Values.NAMESPACE }}
data:
  FUNCTIONS_WORKER_RUNTIME: dotnet
  FUNCTIONS_EXTENSION_VERSION: "~4"
  AZURE_TENANT_ID: {{ print .Values.ARM_TENANT_ID }}
  AZURE_CLIENT_ID: {{ print .Values.ARM_WORKLOAD_APP_ID }}
  SQL_CONNECTION: "{{ .Values.SQL_CONNECTION }}"
  SQL_CONNECTION__clientId: {{ .Values.ARM_WORKLOAD_APP_ID }}  
  EVENTHUB_CONNECTION__clientId: {{ .Values.ARM_WORKLOAD_APP_ID }}  
  EVENTHUB_CONNECTION__fullyQualifiedNamespace: {{ print .Values.EVENTHUB_NAMESPACE_NAME ".servicebus.windows.net" }}
  AzureWebJobsStorage__queueServiceUri: {{ print "https://" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ".queue.core.windows.net" }}
  AzureWebJobsStorage__tableServiceUri: {{ print "https://" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ".table.core.windows.net" }}
  AzureWebJobsStorage__blobServiceUri: {{ print "https://" .Values.WEBJOB_STORAGE_ACCOUNT_NAME ".blob.core.windows.net" }}
  AzureWebJobsStorage__clientId: {{ .Values.ARM_WORKLOAD_APP_ID }} 
