apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventprocessor
  namespace: {{ .Values.NAMESPACE }}
spec:
  selector:
    matchLabels:
      app: keygenerator
      component: eventprocessor
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: "dapr-config"
        dapr.io/app-id: "eventprocessor"
        dapr.io/log-level: "info"
        dapr.io/config-hash: {{ include (print $.Template.BasePath "/components.yaml") . | sha256sum }}
      labels:
        app: keygenerator
        component: eventprocessor
        aadpodidbinding: {{ .Values.MSI_SELECTOR  }} 
    spec:
      containers:
      - name: eventprocessor
        image: {{ print .Values.ACR_NAME "/keygenerator/eventprocessor:" .Values.COMMIT_VERSION }}
        imagePullPolicy: Always
        env:
        - name: EVENTHUB_CONNECTION__credential
          value: managedidentity
        - name: AzureFunctionsJobHost__functions__0
          value: CommandProcessing
        envFrom:
        - configMapRef:
            name: keygeneratorconfig
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 128Mi